name: Check Base Branch

on:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check base branch
        run: |
          git fetch origin
          BASE_BRANCH=$(git rev-parse origin/${{ github.event.pull_request.base.ref }})
          CURRENT_BRANCH=$(git rev-parse HEAD)
          
          if ! git merge-base --is-ancestor $BASE_BRANCH $CURRENT_BRANCH; then
            echo "ERROR: The branch is not based off the latest version of the target branch."
            exit 1
          fi