name: Check Base Branch

on:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check base branch
        run: |
          git fetch origin
          git merge-base --is-ancestor ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF} || (echo "ERROR: The branch is not based off the latest version of the target branch." && exit 1)