name: CI

on: 
  # push: -- just run on PRs for now
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.0
        env:
          POSTGRES_PASSWORD: postgis
          POSTGRES_DB: arches
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false

    steps:
      - name: Check for TypeScript and ESLint issues
        run: |
          echo "Removing yarn.lock due to yarn v1 package resolution issues"
          echo "https://github.com/iarna/wide-align/issues/63"
          cd arches_rdm_example_project
          rm yarn.lock
          yarn && yarn eslint:check && yarn typescript:check

